package com.example.mybatis.dao;

import com.example.mybatis.model.SubjectStudent;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface SubjectStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT_STUDENT
     *
     * @mbg.generated Tue May 03 23:31:01 EEST 2022
     */
    int insert(SubjectStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT_STUDENT
     *
     * @mbg.generated Tue May 03 23:31:01 EEST 2022
     */
    List<SubjectStudent> selectAll();
}